version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/code
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/
volumes:
  mongodb:
